// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VMS.Models;

namespace VMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180819192522_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VMS.Models.Volunteer", b =>
                {
                    b.Property<int>("VolunteerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("ApprovalStatus");

                    b.Property<string>("AvailabilityTimes");

                    b.Property<string>("CentersPreferredToWork");

                    b.Property<bool>("CopyOfVolunteerDriverLicenseOnFile");

                    b.Property<bool>("CopyOfVolunteerSocialSecurityCardOnFile");

                    b.Property<string>("CurrentLicenses");

                    b.Property<string>("EducationalBackground");

                    b.Property<string>("Email");

                    b.Property<string>("EmergencyContactAddress");

                    b.Property<string>("EmergencyContactEmail");

                    b.Property<string>("EmergencyContactHomeWorkPhone");

                    b.Property<string>("EmergencyContactName");

                    b.Property<string>("FirstName");

                    b.Property<string>("HomeWorkCellPhoneNumber");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("SkillsInterests");

                    b.Property<string>("UserName");

                    b.HasKey("VolunteerID");

                    b.ToTable("Volunteers");
                });
#pragma warning restore 612, 618
        }
    }
}
